name: AWS Lab 4
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  grade-lab4:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials via OICD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{vars.AWS_OIDC_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION ?? 'us-east-1'}}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3 requests botocore dotenv
      # - name: Install SAM CLI
      #   run: |
      #     pipx install aws-sam-cli
      #     sam --version
      - name: Verify SAM CLI installation
        run: sam --version

      - name: Build Lambda Layer
        run: |
          mkdir -p src/python_deps/python/lib/python3.11/site-packages
          pip install -r src/python_deps/requirements.txt \
            -t src/python_deps/python/lib/python3.11/site-packages

      - name: Build SAM Application
        run: |
          sam build
          sam deploy \
            --stack-name ${{vars.STACK_NAME ?? 'coderoad-lab-4-aprudencio'}} \
            --region ${{vars.AWS_REGION ?? 'us-east-1'}} \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Get API Gateway URL for manual testing
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{vars.STACK_NAME ?? 'coderoad-lab-4-aprudencio'}} \
            --query 'Stacks[0].Outputs[?OutputKey==`FileGatewayApi`].OutputValue' \
            --output text

      - name: Run Unit tests
        run: |
          pytest tests/unit_test.py

      - name: Run Integration tests
        run: |
          pytest tests/integration_test.py

      #- name: Cleanup - Delete CloudFormation Stack
      #  run: |
      #    aws cloudformation delete-stack --stack-name coderoad-lab-4-aprudencio
